# Generated by Django 3.1 on 2020-08-31 20:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0006_auto_20200831_2237'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='listing_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 8, 31, 22, 38, 16, 724731)),
        ),
    ]
